---
- name: Gather facts from localhost
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Display all gathered facts
      debug:
        var: ansible_facts

    - name: Display specific fact (e.g., Operating System)
      debug:
        msg: "Operating System: {{ ansible_facts['os_family'] }}"

